# kubectl aliases
alias k='kubectl'
alias kx='kubectx'
alias kn='kubens'
alias kgp='kubectl get pods'
alias kgs='kubectl get services'
alias kgd='kubectl get deployments'
alias kgn='kubectl get nodes'
alias kga='kubectl get all'
alias kd='kubectl describe'
alias kdp='kubectl describe pod'
alias kds='kubectl describe service'
alias kdd='kubectl describe deployment'
alias kl='kubectl logs'
alias klf='kubectl logs -f'
alias ke='kubectl exec -it'
alias kaf='kubectl apply -f'
alias kdf='kubectl delete -f'
alias kctx='kubectl config current-context'
alias kns='kubectl config view --minify --output "jsonpath={..namespace}"'

# helm aliases
alias h='helm'
alias hi='helm install'
alias hu='helm upgrade'
alias hup='helm upgrade --install'
alias hd='helm delete'
alias hl='helm list'
alias hla='helm list -A'
alias hs='helm search repo'
alias hr='helm repo'
alias hra='helm repo add'
alias hru='helm repo update'
alias hv='helm show values'
